import type { CatId, Clip } from "../clips";
import type { LibraryItem, LibraryType, Emotion } from "../dualar";
import type { Lang } from "../i18n/base";
import { T } from "../i18n";
import type { ModalName, LoginTab, Tier } from "../types";

export interface ModalsContainerProps {
  modal: ModalName;
  setModal: (m: ModalName) => void;
  loginTab: LoginTab;
  setLoginTab: (t: LoginTab) => void;
  phone: string;
  setPhone: (p: string) => void;
  verifyCode: string;
  setVerifyCode: (c: string) => void;
  sentCode: string;
  handleLoginSubmit: () => void;
  handleRegisterSubmit: () => void;
  handleForgotPassword: () => void;
  handleVerifyCode: () => void;
  handleGuestContinue: () => void;
  fullUnlockConfirmOpen: boolean;
  setFullUnlockConfirmOpen: (v: boolean) => void;
  jetonCount: number;
  tryUnlockFullMode: () => boolean;
  setMode: (m: any) => void;
  premiumOpen: boolean;
  setPremiumOpen: (v: boolean) => void;
  premiumTab: "uyelik" | "jeton";
  serverAdminVerified: boolean;
  tier: Tier;
  setTier: (t: Tier) => void;
  setCurrentTier: (t: Tier) => void;
  setJetonCount: (j: number) => void;
  notify: (msg: string) => void;
  adminAuthOpen: boolean;
  setAdminAuthOpen: (v: boolean) => void;
  adminEmailInput: string;
  setAdminEmailInput: (v: string) => void;
  adminCodeInput: string;
  setAdminCodeInput: (v: string) => void;
  adminError: string | null;
  setAdminError: (e: string | null) => void;
  setAdminGodMode: (v: boolean) => void;
  pickingFor: string | null;
  setPickingFor: (id: string | null) => void;
  clipKind: "img" | "vid";
  setClipKind: (k: "img" | "vid") => void;
  atmosQuery: string;
  setAtmosQuery: (q: string) => void;
  isMasterSürüm: boolean;
  randomizeBackgrounds: (cat?: any) => void;
  atmosCategory: CatId | "all";
  setAtmosCategory: (c: CatId | "all") => void;
  combinedAllClips: Clip[];
  CATEGORY_ICONS: Record<CatId, React.ElementType>;
  lockTip: string | null;
  setLockTip: React.Dispatch<React.SetStateAction<string | null>>;
  accessTier: Tier;
  tierAtLeast: (have: Tier, need: Tier) => boolean;
  filteredClips: Clip[];
  hoveredClip: string | null;
  setHoveredClip: (id: string | null) => void;
  openPremium: (tab?: "uyelik" | "jeton") => void;
  packRights: { kisa: number; uzun: number; tam: number };
  subscriptionEndsAt?: string | null;
  pickClip: (clip: Clip) => void;
  libSearch: string;
  setLibSearch: (s: string) => void;
  libType: LibraryType | "tumu";
  setLibType: (t: LibraryType | "tumu") => void;
  libEmotion: Emotion | "tum";
  setLibEmotion: (e: Emotion | "tum") => void;
  libraryFiltered: LibraryItem[];
  useFromLibrary: (item: LibraryItem) => void;
  addAyah: (s: number, a: number) => void;
  ALL_THEMES: any[];
  themeTier: (id: string) => Tier;
  themeEmoji: (id: string) => string;
  themeId: string;
  setThemeId: (id: string) => void;
  prayerSearch: string;
  setPrayerSearch: (s: string) => void;
  prayerCity: string;
  setPrayerCity: (c: string) => void;
  filteredCities: string[];
  prayerTimings: Record<string, string> | null;
  nextPrayer: { name: string; key: string; diff: number } | null;
  formatRemaining: (ms: number) => string;
  contactType: "oneri" | "sikayet";
  setContactType: (t: "oneri" | "sikayet") => void;
  contactMessage: string;
  setContactMessage: (m: string) => void;
  tosOpen: boolean;
  setTosOpen: (v: boolean) => void;
  tosAccepted: boolean;
  setTosAccepted: (v: boolean) => void;
  legalTab: "tos" | "kvkk" | "gizlilik" | "iade";
  setLegalTab: (t: "tos" | "kvkk" | "gizlilik" | "iade") => void;
  t: (key: keyof (typeof T)["tr"]) => string;
  lang: Lang;
  user?: { email?: string; googleId?: string } | null;
}
