export type { Row } from "../clips-data";

export { NAMAZ_DATA } from "./namaz";
export { MUSAF_DATA } from "./musaf";
export { CICEKLER_DATA } from "./cicekler";
export { YILDIZLAR_DATA } from "./yildizlar";
export { DENIZ_DATA } from "./deniz";
export { GUNBATIMI_DATA } from "./gunbatimi";
export { GECE_DATA } from "./gece";
export { SELALE_DATA } from "./selale";
export { ORMAN_DATA } from "./orman";
export { COL_DATA } from "./col";
export { KAR_DATA } from "./kar";
export { SEHIR_DATA } from "./sehir";
export { CAMI_DATA } from "./cami";
export { DESEN_DATA } from "./desen";
export { GOL_DATA } from "./gol";
export { BULUT_DATA } from "./bulut";
export { CENNET_DATA } from "./cennet";
export { DAGLAR_DATA } from "./daglar";
