import type { CatId } from "./clips";

export interface AdminAtmosphereCategory {
  id: CatId;
  label: string;
  folder: string;
}

const ADMIN_CATEGORY_DATA: Array<[string, string]> = [
  ["adiyat-war-horses", "Savaş Atları"],
  ["aging_elderly_man", "Yaşlı Adam"],
  ["ancient_city_walls", "Antik Şehir Surları"],
  ["ancient_egypt_pyramids", "Antik Mısır Piramitleri"],
  ["ancient_ruins_stone", "Antik Taş Harabeler"],
  ["aurora_borealis_sky", "Kuzey Işıkları"],
  ["belkis-throne-kingdom", "Belkıs'ın Tahtı"],
  ["black_hole_space", "Kara Delik ve Uzay"],
  ["blind_deaf_mute", "Kör, Sağır ve Dilsiz"],
  ["boiling_sulfur_springs", "Kaynayan Kükürt Pınarları"],
  ["cargo_ships_sea", "Denizde Yük Gemileri"],
  ["collapsing_star", "Çöken Yıldız"],
  ["constellation_stars", "Yıldız Takımyıldızları"],
  ["cooked-mud-pottery", "Pişmiş Çamur ve Çömlek"],
  ["darkness_to_light", "Karanlıktan Aydınlığa"],
  ["date_palm_branches", "Hurma Dalları"],
  ["deep_canyon_passages", "Derin Kanyon Geçitleri"],
  ["desert-oasis-sources", "Çöl Vahası ve Kaynaklar"],
  ["earth_crust_layers", "Yerkabuğu Katmanları"],
  ["earthquake_shaking_ground", "Sarsılan Yeryüzü"],
  ["embryo_human_creation", "İnsan Embriyosu ve Yaratılış"],
  ["flying_crow_raven", "Uçan Karga"],
  ["glacier_iceberg_melting", "Eriyen Buzul ve Buzdağı"],
  ["grazing_cattle_sheep", "Otlayan Sığır ve Koyunlar"],
  ["gushing_spring_river", "Çağlayan Pınar ve Nehir"],
  ["hadid_iron_metal", "Demir ve Metal"],
  ["hands_praying_sky", "Göğe Açılan Eller"],
  ["heaven-pomegranate-fruits", "Cennet ve Nar Meyveleri"],
  ["hellfire_volcano_lava", "Cehennem Ateşi ve Lav"],
  ["honeybee_hive_comb", "Bal Arısı ve Petek"],
  ["hudhud-water-suleyman-hoopoe-bird", "Süleyman'ın Hüdhüd Kuşu"],
  ["iron_shield_armor", "Demir Kalkan ve Zırh"],
  ["joseph_deep_well", "Yusuf ve Derin Kuyu"],
  ["justice_scales_balance", "Adalet Terazisi"],
  ["kahf-cave-zara-bowl", "Kehf Mağarası ve Kase"],
  ["karun_treasures_gold", "Karun'un Altın Hazineleri"],
  ["liquid_copper_spring", "Sıvı Bakır Pınarı"],
  ["lizard_in_desert", "Çölde Kertenkele"],
  ["locust_swarm_flying", "Uçan Çekirge Sürüsü"],
  ["lunar_phases_orbit", "Ayın Evreleri ve Yörüngesi"],
  ["luxury_palace_interior", "Lüks Saray İç Mekânı"],
  ["mahshar-wavy-people", "Mahşer ve İnsan Kalabalığı"],
  ["market-place-trade", "Pazar ve Ticaret"],
  ["meteor_shower_stars", "Meteor Yağmuru"],
  ["molten_iron_ore", "Erimiş Demir Cevheri"],
  ["mountains_wool_dust", "Dağlar ve Zirve"],
  ["mud_fertile_soil", "Verimli Çamur Toprağı"],
  ["mustard_seed_macro", "Hardal Tohumu"],
  ["night_sleep_death", "Gece, Uyku ve Ölüm"],
  ["olive_grove_trees", "Zeytinlik Ağaçları"],
  ["paradise_garden_palace", "Cennet Bahçesi ve Saray"],
  ["paradise_rivers_milk", "Cennet Nehirleri ve Süt"],
  ["pearl_coral_diving", "İnci ve Mercan Dalışı"],
  ["pen-ink-writing", "Kalem ve Mürekkep"],
  ["praying_hands_islamic", "İslami Dua Eden Eller"],
  ["regret_sadness_face", "Pişmanlık ve Hüzün"],
  ["rock_carved_houses", "Kayalara Oyulmuş Evler"],
  ["seven_layers_atmosphere", "Yedi Kat Gök ve Atmosfer"],
  ["shining_faces_joy", "Parlayan Yüzler ve Sevinç"],
  ["silk_fabric_textile", "İpek Kumaş"],
  ["silver_goblets_crystal", "Gümüş Kadehler ve Kristal"],
  ["sky_ripping_open", "Yarılmış Gökyüzü"],
  ["smoke_fog_sky", "Dumanlı ve Sisli Gökyüzü"],
  ["solar_eclipse_sun", "Güneş Tutulması"],
  ["spider-rotten-nest", "Örümcek ve Çürük Ağ"],
  ["sprouting_seed_soil", "Filizlenen Tohum"],
  ["stormy_sea_boat", "Fırtınalı Deniz ve Gemi"],
  ["stratosphere_clouds_heavy", "Ağır Stratosfer Bulutları"],
  ["swarming_gnats_mosquito", "Sivrisinek Sürüsü"],
  ["tectonic_plates_fault", "Tektonik Levhalar ve Fay"],
  ["two-sea-merging", "İki Denizin Birleşmesi"],
  ["underground_cave", "Yeraltı Mağarası"],
  ["underwater_currents_dark", "Karanlık Su Altı Akıntıları"],
  ["universe_expansion", "Evrenin Genişlemesi"],
  ["water_well_depth", "Su Kuyusu ve Derinlik"],
  ["water-cycle-cloud-formation", "Su Döngüsü ve Bulut Oluşumu"],
  ["withered_dry_grass", "Kurumuş Otlar"],
  ["wolf_howling_night", "Gece Uluyan Kurt"],
  ["zaqqum_tree_hell", "Cehennem Zakkum Ağacı"],
];

export const ADMIN_ATMOSPHERE_CATEGORIES: AdminAtmosphereCategory[] = ADMIN_CATEGORY_DATA.map(
  ([folder, label]) => ({
    id: `admin_${folder.replace(/[^a-zA-Z0-9]+/g, "_")}` as CatId,
    label: `🎞️ ${label}`,
    folder,
  }),
);
