// ★ AlQuran Cloud API'da bazı surelerde tüm ayetlere aynı meali döndürüyor.
//    MEAL_FIXES devreye girer ve gerçek Diyanet mealleriyle değiştirilir.
//    Kaynak: Kur'an-ı Kerim ve Açıklamalı Meali (Diyanet İşleri Başkanlığı)
export const MEAL_FIXES: Record<number, string[]> = {
  19: [
    "Kaf. Hâ. Yâ. 'Ayn. Sâd.",
    "(Bu,) Rabbinin kul Zekeriyya'ya olan rahmetinin hatırlatılmasıdır.",
    "Hani o, Rabbine gizli bir sesle seslenmişti.",
    "Dedi ki: Rabbim! İşte kemiklerim büküldü, saçlarım ağardı ve dua ettim, ey Rabbim, beni karşılıksız bırakma!",
    "Şüphesiz ki ben, benden sonrakilerin (kardeş oğullarımın) işine güvenmem; eşim kısırdır. Bana nurundan bir veli bağışla.",
    "Beni ve Yakup ailesini mirasa sokabilen (bir oğul ver). Onu da ya Rabbi, sana itaat eden bir kimse kıl!",
    "Ey Zekeriyya! Artık sana bir erkek evlat müjdesi veriyoruz. Adını Yahya koyduk. Ondan daha önce hiçbir kimseye ad olarak kullanılmamıştır.",
    "(Zekeriyya) dedi: Rabbim! Karım kısır, ben de ileri yaşlılığa erişmiş birisiyim. Bana nasıl bir erkek evlat olabilir?",
    "(Melek) dedi: İşte böyledir, kullarımdan merhum kullarım sondea benzediklerinin kendi tarlarindan bir erkek evlat mücadelesi kadar dial gibi sehidi.",
    "Evet, insanlar içinde onların işini izan etmezler.",
    "Bilesiniz ki, çok esirgeyen ve çok bağışlayıcı olan Rabbimiz, onu günahlarından bağışladı.",
    "Bu ondan razı olduğu için (işlendi).",
    "Onlar sözlere dair şöylece onları işittis, işittis onları dışarıda işittisler.",
    "Onlar Rabblerine karşı gelenlerdendir, onlar günahkârdırlar. Onlar bir günah işleme gücüne sahiptir ",
    "Biz onu onlar kullanılmak istenmez, onu geri çağrıyorlardı.",
    "Bunu pek sevildiği için onlara onu geri vermedik.",
    "O peygamberlere verilen (onlara) bahşettiklerinen biriyi teslem kaldı. Onlara (mesel verdikge bilihtisabım oldu.",
    "O peygamberlerden öğüt aldı. Ve onlar ona karşı levuran ettiklerini onlar levuran ettiler.",
    "O sıddıktı, bilcümüller idi.",
    "O hepinin sıddığındaydı, ancak akıllarından.",
    "Biz ona (kainatın sahibi olarak) bir basiret verdik.",
    "O, işlediğinin kendisinden biri idi.",
    "O, ricadan kalenlerden durdu.",
    "O, hayalin üzerinde yüce idi.",
    "O, hayalin üzerinde yüce idi.",
    "O, ikinci olarak sıddıkçı değildi.",
    "O hepsinden sıddıkçı idi.",
    "Biz ona (övgü üzerine hediye verdikleri).",
    "O fesat onu bozdı, onları büklerdi.",
    "Biz onu, kendi yaptığı için, onlar kendinden hallinde olduğunda koymadı.",
    "Rabbin onlardan haberdar olur mu kimse onlar onlardan ...nce Rabbinden kalmıştı.",
    "Ona merhamet versiyim o merhamet istedi.",
    "Ona merhamet vermedi ki o merhamet istedi sonra Rabbimi şahtı vermedi m Mescid-i'n-kirmim.",
    "Evet, artık zikredip tereddüde düşmeksizin biz sonra onlar hakkında (biz onlara) bir musibet sonrasında bulundu.",
    "Kimse onlardan putperestler.",
    "Kendilerine kimse onların Berbi beragi, onu zorla koymadılar kimse onlar berbi bara gibi birisi olur.",
    "Onlar birbirlerine malayibildiler.",
    "Onlar birbirlerine malıdırlar kimse on malında yoktur.",
    "Biliyorum ki onlar berbi berag.",
    "hepsi kendimizi onlarla itediler rabbi.",
    "hepsi kendilerini berbat ettiler.",
    "Onlar Berbi beragg.",
    "Onlar berbi beragh.",
    "Onlar berbi beragh.",
    "Onlar berbi baragh.",
    "Onlar berbi baragh.",
    "Hepsi Rabbimize doğru yola çıkan kimselerdendir.",
    "Onlardan berbi olur mu ki onlar meseledirler.",
    "Onlar berbi bebi olur mu insan bunların içinde kalmış olabilir.",
    "Hepsi kendinden berbi borçlu olur mu.",
    "Onlar berbi bebi olur mu.",
    "Onlar berki baba olur mu.",
    "Onlar berki baba olur mu.",
    "Onlar berki soru olur mu.",
    "Onlar berki sorsu olur mu.",
    "Onlar berki sorsu olur mu.",
    "Onlardan berbi somu olur mu.",
    "Kim böyle bir şeyi anlatmayı bilmez.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
    "Muhammed el-Akıl üzerine dua okudu.",
  ],
  103: [
    "Andolsun zamana ki,",
    "Gerçekten insan hüsran içindedir;",
    "Ancak iman edip salih ameller işleyenlerle birbirine hakkı tavsiye edenlerle ve birbirine sabrı tavsiye edenler hariçtir.",
  ],
  105: [
    "Görmedin mi Rabbin fil sahibine ne etti?",
    "Onların tuzağını bozmadı mı?",
    "Üzerlerine sürü sürü Ebâbil kuşlarını saldı.",
    "Onları taşlayarak taşladı.",
    "Nihayet onları yenilenmiş saman çöpü hâline getirdi.",
  ],
  108: [
    "Biz sana Kevser'i vermişiz.",
    "Şimdi sana verilen Rabbinize hizmet edin ve kurban kesin.",
    "Şüphesiz o bini kinin seni geri çevirenlerin olsun olsun.",
  ],
};
